--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFICION
--------------------------------------------------------

  CREATE TABLE "HR"."AFICION" 
   (	"AFICION_ID" NUMBER(2,0), 
	"NOMBREGUERRA" VARCHAR2(40 BYTE), 
	"EQUIPO_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AFICIONADOS
--------------------------------------------------------

  CREATE TABLE "HR"."AFICIONADOS" 
   (	"AFICIONADOS_ID" NUMBER(9,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DNI" VARCHAR2(20 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CANTICOS
--------------------------------------------------------

  CREATE TABLE "HR"."CANTICOS" 
   (	"CANTICOS_ID" NUMBER(20,0), 
	"CANCIONES" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "HR"."EQUIPO" 
   (	"EQUIPO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "HR"."EQUIPOS" 
   (	"EQUIPO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"FECHAFUNDACION" DATE, 
	"COLORES" VARCHAR2(20 BYTE), 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."EQUIPOS"."EQUIPO_ID" IS 'Clave primaria';
   COMMENT ON COLUMN "HR"."EQUIPOS"."NOMBRE" IS 'Nombre del equipo';
   COMMENT ON COLUMN "HR"."EQUIPOS"."FECHAFUNDACION" IS 'Fecha de Fundacion del Equipo';
   COMMENT ON COLUMN "HR"."EQUIPOS"."COLORES" IS 'Colores de las camisetas';
--------------------------------------------------------
--  DDL for Table ESTADIO
--------------------------------------------------------

  CREATE TABLE "HR"."ESTADIO" 
   (	"ESTADIO_ID" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "HR"."JUGADORES" 
   (	"JUGADORES_ID" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"SUELDO" NUMBER(7,0), 
	"EQUIPO_ID" NUMBER(2,0), 
	"APELLIDOS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOMBREGUERRA
--------------------------------------------------------

  CREATE TABLE "HR"."NOMBREGUERRA" 
   (	"NOMBREGUERRA_ID" VARCHAR2(100 BYTE), 
	"TITULOS" VARCHAR2(20 BYTE), 
	"AFICION_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AFICION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."AFICION_PK" ON "HR"."AFICION" ("AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AFICIONADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."AFICIONADOS_PK" ON "HR"."AFICIONADOS" ("AFICIONADOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CANTICOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."CANTICOS_PK" ON "HR"."CANTICOS" ("CANTICOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EQUIPOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."EQUIPOS_PK" ON "HR"."EQUIPOS" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTADIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."ESTADIO_PK" ON "HR"."ESTADIO" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JUGADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."JUGADORES_PK" ON "HR"."JUGADORES" ("JUGADORES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOMBREGUERRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."NOMBREGUERRA_PK" ON "HR"."NOMBREGUERRA" ("NOMBREGUERRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "HR"."AFICION" ADD CONSTRAINT "AFICION_PK" PRIMARY KEY ("AFICION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."AFICION" MODIFY ("NOMBREGUERRA" NOT NULL ENABLE);
  ALTER TABLE "HR"."AFICION" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AFICIONADOS
--------------------------------------------------------

  ALTER TABLE "HR"."AFICIONADOS" ADD CONSTRAINT "AFICIONADOS_PK" PRIMARY KEY ("AFICIONADOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."AFICIONADOS" MODIFY ("AFICIONADOS_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."AFICIONADOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "HR"."CANTICOS" ADD CONSTRAINT "CANTICOS_PK" PRIMARY KEY ("CANTICOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CANTICOS" MODIFY ("CANCIONES" NOT NULL ENABLE);
  ALTER TABLE "HR"."CANTICOS" MODIFY ("CANTICOS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "HR"."EQUIPOS" ADD CONSTRAINT "EQUIPOS_PK" PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."EQUIPOS" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."EQUIPOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."EQUIPOS" MODIFY ("FECHAFUNDACION" NOT NULL ENABLE);
  ALTER TABLE "HR"."EQUIPOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADIO
--------------------------------------------------------

  ALTER TABLE "HR"."ESTADIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."ESTADIO" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "HR"."ESTADIO" ADD CONSTRAINT "ESTADIO_PK" PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."ESTADIO" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "HR"."JUGADORES" ADD CONSTRAINT "JUGADORES_PK" PRIMARY KEY ("JUGADORES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."JUGADORES" MODIFY ("JUGADORES_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."JUGADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."JUGADORES" MODIFY ("SUELDO" NOT NULL ENABLE);
  ALTER TABLE "HR"."JUGADORES" MODIFY ("APELLIDOS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOMBREGUERRA
--------------------------------------------------------

  ALTER TABLE "HR"."NOMBREGUERRA" MODIFY ("TITULOS" NOT NULL ENABLE);
  ALTER TABLE "HR"."NOMBREGUERRA" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."NOMBREGUERRA" ADD CONSTRAINT "NOMBREGUERRA_PK" PRIMARY KEY ("NOMBREGUERRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."NOMBREGUERRA" MODIFY ("NOMBREGUERRA_ID" NOT NULL ENABLE);
