--------------------------------------------------------
-- Archivo creado  - martes-enero-24-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBIDA_SALARIO
--------------------------------------------------------

  CREATE TABLE "HR"."SUBIDA_SALARIO" 
   (	"SALARIO_ID" NUMBER(8,0), 
	"SALARIO_ANTERIOR" NUMBER, 
	"SALARIO_POSTERIOR" NUMBER, 
	"FECHA_SUBIDA" DATE, 
	"EMPLOYEE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBIDA_SALARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SUBIDA_SALARIO_PK" ON "HR"."SUBIDA_SALARIO" ("SALARIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger SUBIDA_SALARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."SUBIDA_SALARIO_TRG" 
BEFORE INSERT ON SUBIDA_SALARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."SUBIDA_SALARIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SUBIDA_SALARIO_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."SUBIDA_SALARIO_TRG1" 
BEFORE INSERT ON SUBIDA_SALARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.SALARIO_ID IS NULL THEN
      SELECT SUBIDA_SALARIO_SEQ1.NEXTVAL INTO :NEW.SALARIO_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HR"."SUBIDA_SALARIO_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBIDA_SALARIO
--------------------------------------------------------

  ALTER TABLE "HR"."SUBIDA_SALARIO" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."SUBIDA_SALARIO" ADD CONSTRAINT "SUBIDA_SALARIO_PK" PRIMARY KEY ("SALARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."SUBIDA_SALARIO" MODIFY ("FECHA_SUBIDA" NOT NULL ENABLE);
  ALTER TABLE "HR"."SUBIDA_SALARIO" MODIFY ("SALARIO_POSTERIOR" NOT NULL ENABLE);
  ALTER TABLE "HR"."SUBIDA_SALARIO" MODIFY ("SALARIO_ANTERIOR" NOT NULL ENABLE);
  ALTER TABLE "HR"."SUBIDA_SALARIO" MODIFY ("SALARIO_ID" NOT NULL ENABLE);
